#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomListView.Resource", IsApplication=true)]

namespace CustomListView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int reminder_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_save_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edit_text_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rounded_edit_text = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080018
			public const int Heading = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int List = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int Text = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int Text1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int Text2 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int Text3 = 2131230741;
			
			// aapt resource value: 0x7f08000f
			public const int alaramTime = 2131230735;
			
			// aapt resource value: 0x7f080016
			public const int alarmActive = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int alarmName = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int btnCancelAddAlarm = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int btnCancelEditAlarm = 2131230743;
			
			// aapt resource value: 0x7f08000b
			public const int btnSaveAlarm = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int button1 = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int button2 = 2131230745;
			
			// aapt resource value: 0x7f080008
			public const int cBoxFri = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int cBoxMon = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int cBoxSat = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int cBoxSun = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int cBoxThu = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int cBoxTue = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int cBoxWed = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public const int relativeLayout1 = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int reminderList = 2131230722;
			
			// aapt resource value: 0x7f080011
			public const int stopAlarm = 2131230737;
			
			// aapt resource value: 0x7f080000
			public const int txtAlarmName = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int txtAlarmTime = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int txtReminder = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddAlarm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddAlarmFrag = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int alarm = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int custom = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditAlarm = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int reminder_prompt = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
